export const storage = {
    RESIDENTI_BUILDING: 'EDIFICIO',
    RESIDENTI_USER: 'IDUSER',
    RESIDENTI_APARTAMENT: 'APARTAMENTO',
    RESIDENTI_MODAL: 'MODAL',
    RESIDENTI_REMEMBER_USER: 'REMEMBER_USER'
}